package de.paulmethfessel.lezer.annotator

/** Simplifies the error messages generated by Grammar-Kit, e.g. `'}' expected, got '@skip'`. */
object LezerErrorMessages {
    private val EXPECTED = Regex("""^(.*) expected(?:, got (.*))?$""", RegexOption.DOT_MATCHES_ALL)

    private val CLOSERS = setOf("'}'", "')'", "']'", "'>'")
    private val SEPARATORS = setOf("','")

    /** Tokens that may continue an expression but are never required, they only add noise. */
    private val CONTINUATIONS = setOf("'!'", "'~'", "'*'", "'+'", "'?'", "'|'", "'.'")

    fun simplify(description: String): String {
        val match = EXPECTED.matchEntire(description) ?: return description
        val expected = splitAlternatives(match.groupValues[1])
        val got = match.groups[2]?.value

        var relevant = expected.filter { it !in CONTINUATIONS }.ifEmpty { expected }
        // A missing closing delimiter is the most likely cause, everything else could only continue the current construct
        if (relevant.any { it in CLOSERS }) relevant = relevant.filter { it in CLOSERS || it in SEPARATORS }

        val alternatives = relevant.distinct()
        val text = if (alternatives.size == 1) {
            alternatives.single()
        } else {
            alternatives.dropLast(1).joinToString(", ") + " or " + alternatives.last()
        }
        return if (got != null) "$text expected, got $got" else "$text expected"
    }

    /** Splits `a, b or c` into its items. Items are either quoted tokens (which may contain `,`) or plain names. */
    private fun splitAlternatives(text: String): List<String> {
        val items = mutableListOf<String>()
        var rest = text
        while (rest.isNotEmpty()) {
            val item = if (rest.startsWith("'")) {
                val end = rest.indexOf('\'', 1)
                if (end < 0) rest else rest.substring(0, end + 1)
            } else {
                rest.substringBefore(", ").substringBefore(" or ")
            }
            items += when (item) {
                // Grammar-Kit doesn't quote angle brackets, as it uses them for rule names
                "<", ">" -> "'$item'"
                else -> item.removeSurrounding("<", ">")
            }
            rest = rest.removePrefix(item).removePrefix(", ").removePrefix(" or ")
        }
        return items
    }
}
